version: '3.4'

services:
  dev:
    build: .
    container_name: escola_api_dev
    command: npm run dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:cached
